In [52]:
import cv2
import numpy as np
import glob
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split


In [53]:
# İmage List
image_list=[]

In [54]:
img_size = 64

In [55]:
# dosyadan resimleri çekip işleme yapıyoruz ardından listeye atıyoruz
for i in range(0,10):
    file = glob.glob(f"/content/drive/MyDrive/spectrograms/{i}/*.png")
    # dosyadaki resim sayısını ekrana bastırıyoruz
    for spectrogram in file:
        try:
            # resim okuma
            img = cv2.imread(spectrogram,cv2.IMREAD_GRAYSCALE)
            # resize 
            resized_img = cv2.resize(img,(img_size,img_size))
            # grayscale
            # normalizasyon
            image_list.append([resized_img,i])
        except Exception as e:
            pass
            

In [56]:
# label list
label_list=[]
image_raw_list=[]

In [57]:
# image_listi label list ve image_raw_list ikiye ayırıyoruz
for data in image_list:
    label = data[1]
    img= data[0]
    label_list.append(label)
    image_raw_list.append(img)

In [58]:
print(image_raw_list[800])

[[249   0   0 ...   0   0   0]
 [249   0   0 ...   0   0   0]
 [249   0   0 ...   0   0   0]
 ...
 [249 185 139 ... 156 125 124]
 [249 130 212 ... 155 207 194]
 [254 249 249 ... 249 249 249]]


In [59]:
# image listesini reshape yapıyoruz
image_raw_list = np.array(image_raw_list).reshape(-1,img_size,img_size,1)

In [60]:
print(image_raw_list[800])

[[[249]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]

 [[249]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]

 [[249]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]

 ...

 [[249]
  [185]
  [139]
  ...
  [156]
  [125]
  [124]]

 [[249]
  [130]
  [212]
  ...
  [155]
  [207]
  [194]]

 [[254]
  [249]
  [249]
  ...
  [249]
  [249]
  [249]]]


In [61]:
x_train,x_temporary,y_train,y_temporary = train_test_split(image_raw_list,label_list,train_size=0.8)

In [62]:
x_test,x_val,y_test,y_val = train_test_split(x_temporary,y_temporary,train_size=0.5)

In [63]:
# dataseti kaydetme
np.save("/content/mobel_Data/X_train.npy",x_train)
np.save("/content/mobel_Data/X_test.npy",x_test)
np.save("/content/mobel_Data/X_val.npy",x_val)
np.save("/content/mobel_Data/Y_train.npy",y_train)
np.save("/content/mobel_Data/Y_test.npy",y_test)
np.save("/content/mobel_Data/Y_val.npy",y_val)